### PR TITLE
Use docker-login action, update poetry.lock

### PR DESCRIPTION
**Pull request by reconman**
Since DOCKERHUB_PASSWORD doesn't seem to work, try using a token as described in https://github.com/docker/login-action#docker-hub.

The secret needs to be named DOCKERHUB_TOKEN.

### CODE REVIEW

**Comment by lavie** [comment]
Thanks. Ran it now with the new token and secret name. Same results. 
I'll figure it out though. Thanks for contributing the github action change.

**Comment by lavie** [comment]
possibly related: https://github.com/docker/login-action/issues/65

**Comment by reconman** [comment]
Github states that workflows triggered by PRs of forks cannot access any secrets in the original repository, including DOCKERHUB_PASSWORD and DOCKERHUB_TOKEN.

On second thought, is the `docker login` actually needed for PRs? `make test` doesn't run any docker commands, it seems.

**Comment by lavie** [comment]
I think the login was added to the CI because of rate limiting by dockerhub for anonymous (not logged-in) pulls.

**Comment by lavie** [comment]
regardless though, the main contribution flow I want to establish is that contributors could submit PRs and have them fully tested, and be able to iterate on broken builds, without me having to clone their PRs. if this is not achievable with GitHub Actions I might have to look elsewhere.

**Comment by reconman** [comment]
With the current state of the PR, the Docker rate-limiting is the only limitation for future contributors, but I don't think that this will be an issue. I've never faced Dockerhub rate limiting in my Github workflows.

The main reason for forks not seeing secrets is that I could modify the ci.yml in my fork in such a way that I could extract your password or token. Any workarounds are dangerous.

In my opinion, this PR can be merged now.

**Comment by lavie** [comment]
I did get some rate limiting on this repo, hence the addition of the login to the CI. But I'm happy to give it a try again and hopefully Dockerhub are less stingy with their rate limiting nowadays.

**Comment by lavie** [comment]
Indeed. Works well now. Published 1.4.1 just now from `master`.
🙏🏻

**Comment by reconman** [comment]
I could also add the docker-login optionally for pushes, so if you do a lot of commits, you won't be rate-limited.

How does that sound?

**Pull request merged**
