### PR TITLE
added privileged and labels

### PR DESCRIPTION
**Pull request by HuPonya**
#23 added privileged

### CODE REVIEW

**Comment by lavie** [comment]
thanks, @HuPonya. If you would be so kind as to add a bit of coverage to this in `test_runlike.py` I would appreciate it.

**Comment by HuPonya** [comment]
Yes, I added test case. please see if ok.

**Comment by HuPonya** [comment]
#20 add catch labels

**Comment by lavie** [comment]
merged. Thank you!

**Pull request closed without merging**
