### PR TITLE
Push Docker images via Github Actions 

### PR DESCRIPTION
**Pull request by reconman**
Docker stopped autobuilding Github repositories in June 2021, therefore it needs to be pushed manually with Github Actions. https://www.docker.com/blog/changes-to-docker-hub-autobuilds/

This PR implements that. Additionally, ARM CPUs will be supported by making use of QEMU, which creates one Docker image per CPU architecture.

### CODE REVIEW

**Comment by lavie** [comment]
Thanks! Just a heads up that it's going to take me a bit of time to fix the current CI problem that has the builds breaking.

**Comment by reconman** [comment]
> Thanks! Just a heads up that it's going to take me a bit of time to fix the current CI problem that has the builds breaking.

What's the issue? The first build broke because docker login didn't work, but now I changed it to the docker-login Github action.

**Comment by reconman** [comment]
Seems like you don't have your Docker password stored in the repository secrets?

**Comment by reconman** [comment]
After I spent some time reading the Makefile, I noticed that part of it is docker push.

It's not that easy to keep the same functionality while publishing for multiple CPU architectures.

The current state of this PR should not be merged.

**Comment by lavie** [comment]
No problem.
The change you made to the docker-login part, though, is quite useful by itself. If you'd like to submit it as its own PR I'd be happy to merge it (once I figure out why the password isn't being passed along properly).
Thanks @reconman

**Pull request closed without merging**
