### PR TITLE
Add log-driver and log-opt.

### PR DESCRIPTION
**Pull request by anryko**
Added `--log-driver` and `--log-opt` support.

### CODE REVIEW

**Comment by lavie** [comment]
@anryko thanks for this enhancement, and for also adding the test coverage.

I'm wondering if you'd mind to tweak the implementation, so that if the default log driver is used (without any config values) then the output does not include any mention of log-driver at all?

This way the output is much cleaner when defaults are used.

**Comment by anryko** [comment]
Ready.

**Comment by anryko** [comment]
When can I expect this update to be available in pypi?

**Comment by lavie** [comment]
Tuesday the latest.

**Comment by lavie** [comment]
@anryko it's out.

**Pull request merged**
